apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "prima_tracing.rs"
  description: "Utilities for configuring a tracing subscriber with support for logging"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-developer-experience"
  system: prima.it
