[package]
name = "prima-tracing"
version = "0.2.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Enrico Risa <enrico.risa@prima.it>"]
edition = "2018"
description = "Prima.it opentelemetry standard library"
repository = "https://github.com/primait/prima_tracing.rs"

[features]
default = ["prima-logger"]
prima-logger = ["tracing-log"]
prima-telemetry = ["tracing-opentelemetry", "opentelemetry", "opentelemetry-zipkin"]
prima-logger-json = ["prima-logger"]
prima-logger-datadog = ["prima-logger-json", "opentelemetry"]

[[example]]
name = "custom-json-subscriber"
path = "examples/custom_json_subscriber.rs"
required-features = ["prima-logger-json"]

[[example]]
name = "custom-subscriber"
path = "examples/custom_subscriber.rs"
required-features = ["prima-logger-json"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
opentelemetry = { version = "0.16", features = ["rt-tokio-current-thread"], optional = true }
opentelemetry-zipkin = { version = "0.14", features = ["reqwest-client"], default-features = false, optional = true }
tracing = { version = "0.1", features = ["max_level_debug", "release_max_level_info"] }
tracing-opentelemetry = { version = "0.16", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = { version = "0.1", optional = true }

# serialization/deserialization
serde = { version = "^1.0", features = ["derive"] }
# json serialization
serde_json = "^1.0"

# dates
chrono = { version = "^0.4", features = ["serde"] }

uuid = { version = "^0.8", features = ["serde", "v4"] }

[dev-dependencies]
actix-web = "4.0.0-beta.13"
tracing-actix-web = { version = "0.5.0-beta.1", features = ["opentelemetry_0_16"] }
prima_bridge = "0.8"
